### ISSUE TITLE
[Request]: WazySurGithub

### ISSUE THREAD

**Issue by WazySurGithub** [JohnB17/ptero-eggs#1]
### Packages

php xmlwriter (don't know the package name)

### Platforms

AMD64

### License

- [X] I agree to abide by the MIT License in this Repository

**Comment by JohnB17** [comment]
I have finished! Simply install the egg and change the Docker image to this URL: 
```
ghcr.io/johnb17/nginx-ptero:wazysurgithub-xmlwriter
```
