### ISSUE TITLE
[Request]: Need webhost egg with php 5.4

### ISSUE THREAD

**Issue by barlap** [JohnB17/ptero-eggs#3]
### Packages

Hello.
It is possible to add older versions of php? 
I need php 5.4 with schedtool to run an old platform who can't run on newer php versions.

### Platforms

Both

### License

- [X] I agree to abide by the MIT License in this Repository

**Comment by JohnB17** [comment]
Will do after work.

**Comment by barlap** [comment]
ok

**Comment by JohnB17** [comment]
I have finished! Simply install the egg and change the Docker image to this URL: 
```
ghcr.io/johnb17/nginx-ptero:barlap-php5
```

**Comment by barlap** [comment]
Installed and i'm getting this error.
I will let this comment here just in case
![image](https://user-images.githubusercontent.com/18375400/193259826-86d94919-5e3d-4007-a9cf-0648db6cb8e8.png)

**Comment by JohnB17** [comment]
```sh
#!/bin/ash
rm -rf /home/container/tmp/*

echo "⟳ Starting PHP-FPM..."
/usr/bin/php-fpm5 --fpm-config /home/container/php-fpm/php-fpm.conf --daemonize

echo "⟳ Starting Nginx..."
echo "✓ Successfully started"
/usr/sbin/nginx -c /home/container/nginx/nginx.conf -p /home/container/
```
Putting here for future reference or anyone else that needs this.
