### ISSUE TITLE
[Request]: Bali0531Real

### ISSUE THREAD

**Issue by Bali0531Real** [JohnB17/ptero-eggs#8]
### Packages

![image](https://github.com/JohnB17/ptero-eggs/assets/164927809/77154a78-34ac-48a2-9e9d-9f28e25d3695)
To fix this error
I think ext-mongodb or idk how its called, 

### Platforms

Both

### License

- [X] I agree to abide by the MIT License in this Repository

**Comment by JohnB17** [comment]
Hello, I am currently working on your request. I was inconsistent with this service for a while, so I have a backlog of 2 other people. This is a simple one I could complete quickly, so don't worry about waiting too long.

**Comment by JohnB17** [comment]
I have finished! I have tested the image, just swap out the docker image for this URL and you should be good to go.
```
ghcr.io/johnb17/nginx-ptero:bali0531real-mongodb
```
If anything goes wrong, please reopen this issue.
